### ISSUE TITLE
Csv Writers

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#10]
Originally reported by: **Jens Buss (Bitbucket: [jebuss](http://bitbucket.org/jebuss), GitHub: [jebuss](http://github.com/jebuss))**

----------------------------------------

Hi,

It would be good to have a "swarm" of CsvWriter processors that could do the following:
1. write all keys of a data item to Csv exept for a list of keys="key1, key2,..", e.g. DataCalibrated
2. write all keys fitting to a  given regular expression

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/10

**Comment by MaxNoe** [comment]
This can be done using the streams CsvWriter using the Keys class
