### ISSUE TITLE
TODOs ROOTAsciiWriter

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#100]
It has been deprecated for a while now, because it does not work for some ROOT Versions.

To get rid of the deprecation, the following things should work:
- [ ] Current root version
- [ ] Transforming `PixelSet` into int array 
- [ ] Support for different lengths arrays, see https://root.cern.ch/doc/master/classTBranch.html#ae30a4edb372811b4f02b485b7b0dfaca
- [ ] Timestamps to ISO string

**Comment by mahnen** [comment]
I was using it for comparing FACT to MAGIC data. Would be nice for me to keep this function in.

**Comment by MaxNoe** [comment]
If you just want to have a root file at the end of the day, you could consider using the `JSONWriter` like this:

```{xml}
<fact.io.JSONWriter url="file:test.json"  keys="key1,key2" specialDoubleValuesAsString="true" />
```

And use `pandas` and `root_pandas` like this:

```{python}
import pandas as pd
import root_pandas as rpd

data = pd.read_json('test.json')
data.to_root('test.root', 'treename')
```

**Comment by MaxNoe** [comment]
@mahnen, @ftemme 

Could you describe your workflow with this processor? How do you convert the `.csv` to `.root`?

**Comment by MaxNoe** [comment]
We discussed yesterday, that we want to keep this processor, and that it will be undeprecated if the todos in the first post are done.

**Comment by mahnen** [comment]
Thanks, if you like I could still report on the workflow though. Exactly as you mentioned, I use the TTree.ReadFile:

`	if ( FactFilePaths.size() != FactRootFilePaths.size() ){
		// convert the txt files to root files
		for (std::string OneFactFile : FactFilePaths )
		{
			//generate a root tree file from the fact-tools output 
			//in order to read it in with the ROOT chain method later.
			std::string outbuf = OneFactFile;
			outbuf = outbuf.replace( outbuf.end()-3,outbuf.end(),"root");
			
			TFile f( outbuf.c_str() , "RECREATE");
			TTree fTree;
			fTree.ReadFile( OneFactFile.c_str() ,"",' '); 
			fTree.SetDirectory( &f );
			fTree.Write("",TObject::kOverwrite);
			f.Close();
			//std::cout << "file to be opened: " << OneFactFile << std::endl;
			//std::cout << "file to be written: " << outbuf << std::endl;
		}
	}`

**Comment by MaxNoe** [comment]
I think nobody is using and anymore and with good reason.
