### ISSUE TITLE
Viewer: Structure displayable objects better

### ISSUE THREAD

**Issue by ftemme** [fact-project/fact-tools#104]
At the moment, there are a larger number of objects in the viewer which can be selected to be displayed in the viewer. Would be nice to structure this a little bit better. For example:
- [ ] Put all pixelset objects in a separate drop-down menu
- [ ] Put colormaps into submenu
- [ ] Show kind of overlay

**Comment by MaxNoe** [comment]
We won't put efforts into the gui anymore
