### ISSUE TITLE
TODOs refactoring 9 und 10te Februar

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#107]
#### XML für analyse
- [ ] selbes xml für daten und MC
- [x] keys -> namenshierarchie 
- [ ] 1 single file 
- [x] basierend auf hierarchie -> default für keys
- [ ] Dokumentation: Konzept.  API (generated), Tutorial?
- [ ] Writer kriegen ein File parameter und keine SourceURL

**Comment by mackaiver** [comment]
Prosposal for naming conventions:

0. all lowercase letters. seperate by underscores _
1.  raw data and all data that is basically voltage curves will be prepended by `raw:`
2.  monte carlo features as found in the ceres output will be prepended by `mc:`

**Comment by MaxNoe** [comment]
We use milestones for this now
