### ISSUE TITLE
Move stuff into the distribution Object.

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#11]
Originally reported by: **mackaiver (Bitbucket: [mackaiver](http://bitbucket.org/mackaiver), GitHub: [mackaiver](http://github.com/mackaiver))**

---

Currently alot of stuff is being done in the DistributionFromShower processor. To make it testable someone should move the calculations into smaller modules inside the Distribution object.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/11

**Comment by MaxNoe** [comment]
This is basically the same as #230
