### ISSUE TITLE
Log error message if functional_tests fail

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#113]
We should log the error message if one of the xmls in studies fails to execute.

**Comment by MaxNoe** [comment]
see #112

**Comment by mackaiver** [comment]
This was fixed. And then it was unfixed if I remember correctly.

https://bitbucket.org/cbockermann/streams/issues/50/all-exceptions-get-caught

**Comment by MaxNoe** [comment]
And no it's fixed again.
