### ISSUE TITLE
progressbar would be nice

### ISSUE THREAD

**Issue by dneise** [fact-project/fact-tools#133]
when testing something on a single file, a progressbar would be nice.

**Comment by mackaiver** [comment]
Would some logging output as in 

      10% completion
      20% completion
      ...
      100% 
      //next file starts here
      10% completion
      ....

suffice?
I could add soemthing like that to the zfits stream I think. 
In that cas

**Comment by dneise** [comment]
I guess that would be nice already.

**Comment by MaxNoe** [comment]
I then always use `<fact.io.PrintKeys keys="EventNum"/>`, also not that streams have a `limit="<N>"` option. I think this suffices for local testing
