### ISSUE TITLE
pixel-map.csv has CarriageReturn (\CR) line ending

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#143]
On my Ubuntu 14.04, no program (vi, less, wc, numpy.genfromtxt(),...) can read the pixel-map.csv file because it uses only the \CR line ending. When I change the line ending to unix style \LF everything is fine for me. May I fix this in the master for all of us, or do you have machines which demand \CR?

**Comment by mackaiver** [comment]
Not that I'm aware of. Does windows need Carriage Return? I think we can change it.

**Comment by MaxNoe** [comment]
No, Windows needs `\LF\CR` not only `\CR`. Also git on windows handles this. When you checkout, `\LF` is replaced by `\LF\CR` and the other way around when you commit.

**Comment by mackaiver** [comment]
So lets change it right?

**Comment by jebuss** [comment]
+1
