### ISSUE TITLE
Use ranges for defining hardware setups in the CalibrationService

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#146]
The `ConstantCalibService` uses a `TreeSet` for storing `HardwareConfiguration`. Which works fine. Maybe we want to use a `TreeRangeSet` to make `HardwareConfiguration` valid for ranges of dates.
This is more of an enhancement than and urgent task I guess.

**Comment by MaxNoe** [comment]
Ranges are implicly defined by the start date. I think we do not really gain something by explictly defining ranges.
