### ISSUE TITLE
Flag 27sec events

### ISSUE THREAD

**Issue by dneise** [fact-project/fact-tools#150]
We (Zurich) think the 27sec events should be skipped entirely during analysis.

An event is a 27sec event if many pixels are saturated for > 100 slices.
(we assume, if one pixel saturates for >100 slices ... then all do ... so maybe checking one pixel is already enought... but more are better.

We think flagging these files as "Is27SecondEvent" would be good.

We further think in Jens `CorrectSaturation` processor is well suited to find these.

**Comment by jebuss** [comment]
In principle i think that this is reasonable. However, we I assume that these events won't survive the background suppression. Therefore I guess it would not make a difference weather we keep them or not. Or do you see some issue besides the disposal of runtime? I only wonder if the early suppression of these events might have some systematics with regards to none 27s-Events

**Comment by dneise** [comment]
Ah, we talked a bit further and now agreed that simply flagging them as 27sec event is enough.

If it gets killed in a cut, fine.If not, it can be found.

**Comment by jebuss** [comment]
+1
