### ISSUE TITLE
Get rid of redundant XML modules

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#171]
The following list of standard module XMLs is more or less identical for the MC and Data chain.

resources/default/mc/calibration_mc.xml
resources/default/mc/cleaning_mc.xml
resources/default/mc/extraction_mc.xml
resources/default/mc/parameterCalc_mc.xml
resources/default/mc/parameterCalc_mc_dispRF.xml
resources/default/mc/pedestalParameters_mc.xml
resources/default/mc/sourceParameter_mc.xml

resources/default/data/calibration.xml
resources/default/data/cleaning.xml
resources/default/data/extraction.xml
resources/default/data/parameterCalc.xml
resources/default/data/parameterCalc_dispRF.xml
resources/default/data/pedestalParameters.xml
resources/default/data/sourceParameter.xml

I think we can reduce this redundancy to only the few processors that are different for data and mc

**Comment by mackaiver** [comment]
:+1:
