### ISSUE TITLE
AuxPoints contain 0 values although no 0s are in the file

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#179]
This leads to strange behaviour, since the time is then 1970-1-1

**Comment by MaxNoe** [comment]
This seems to happen for the last 4 rows of every aux file. 

The FITSStream puts zeros for all keys.

**Comment by dneise** [comment]
I've seen 0s in the Time column of aux files yesterday while looking at rates with astropy.Table.read. So at least in some files there are in fact zeros as Times... 

Apparebtly a bug somewhere in FACT++ nobody bothered to report or fix so far, including me of course.

You sure, the file u talking about might not be one of those suffering from said bug?

**Comment by dneise** [comment]
Oh okay

**Comment by MaxNoe** [comment]
I checked the files with astropy.table.read and there are no rows with all zeros in the test file.

**Comment by mackaiver** [comment]
Can you give an example file?

**Comment by MaxNoe** [comment]
Our test data aux files.

**Comment by MaxNoe** [comment]
This seems to be a problem of the `fact.io.FitsStream`. I ported the AuxService to our new HDUReader here: #181 and the problem seems to be gone.

**Comment by mackaiver** [comment]
I guess this can be closed now.

**Comment by MaxNoe** [comment]
The corresponding PR is not yet merged. It still has conflicts that need to be resolved

**Comment by MaxNoe** [comment]
Should be solved by now
