### ISSUE TITLE
single pulse extractor output is not yet size efficient, baselines too fine

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#182]
File size comparison for FACT run 20151001_011 with fact-tools 0.17.2 pass2    

| file type | size [MB] | reduction [rel.] |
| ------------- | ------------- |-----------|
| zfits  | 2935  | 1.0 |
| fact-tools jsonl.gz  | 305 | 9.6 |
| baseline in doubleSignDigits = 3 jsonl.gz  | 170 | 17.3 |
| optimized jsonl.gz  | 154 | 19.1 |
| optimized and truncated time lines jsonl.gz  | 94 | 31.2 |
| optimized, truncated time lines, and no baselines jsonl.gz  | 69 | 42.5 |

The baselines (useful for time series reconstruction) are a mayor contribution to the output size as they are stored as floats:
```"PhotonArrivalsBaseLine":[-0.9346934899690481,-0.914864300604518, ...```

This may be optimized by storing the baseline in e.g. centi 1pe amplitudes which is still fine enough:
```"PhotonArrivalsBaseLine100":[-93,-91, ...```

**Comment by dneise** [comment]
started working on it, c.f https://github.com/fact-project/fact-tools/commit/da29965ddc243c01f6140dc4aa5754ca6e0ea935

**Comment by MaxNoe** [comment]
The facttools JSONWriter has the option `doubleSignDigits` which sets the number of decimal places for doubles.

**Comment by dneise** [comment]
yes, but this is globally affecting the precision, right? The proposal is to only change this for the BaseLines

**Comment by MaxNoe** [comment]
Yes, i just wanted to mention it in case you were not aware of the option. (And I don't think we have anything that would require the default of 8 digits)

**Comment by dneise** [comment]
closed by #186
