### ISSUE TITLE
single pulse extractor output truncation option

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#183]
The output of the single pulse extractor has artefacts in its beginning and its end.
Currently (fact-tools 0.17.2 spe pass2), and there is no air shower signal beyond slice ~ 130.
We want an option to truncate the output of the extractor, to remove artifacts and reduce output size. 
The truncation shall be controllable via parameters for the extraction processor. Defaults might be start: 15ns (30slices) and end: 65ns (130slices). 

All videos of the photon stream I have shown yet were reduced to 15ns-65ns, or even less anyhow.

| |   | start slice | end slice | remarks |
|---|---|---|---|---|
| exists | raw ROI | 0 | 300 | |
| exists | 1pe extraction range | 20 | 245 | truncate time marker and analog artifacts in the beginning |
| proposal | 1pe output range | 30 | 130 | truncate 1pe extraction artifacts and focus on air shower photons |

**Comment by dneise** [comment]
solved by #185
