### ISSUE TITLE
Create PhotonStream package

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#198]
create a `fact.photonstream` package and move all processors that are related to the photon stream to this package, e.g.:

* `fact.extraction.SinglePulseExtraction`
* `fact.utils.PhotonStream2ArrivalTime`
* `fact.utils.PhotonStream2NumberOfPhotons`
* `fact.utils.ConvertSinglePulses2Timeseries`

**Comment by relleums** [comment]
It is not only extraction any more. We also want to collect tools here for the reconstruction of photon charge and arrival time from the photon-stream.

what shall it be?
```
fact.PhotonStream.
fact.photonstream.
fact.photon_stream.
fact.photon-stream.
```

**Comment by MaxNoe** [comment]
You missed lower-camel case: photonStream. I would go for upper camel case: `fact.PhotonStream`

**Comment by dneise** [comment]
all other packages are *all lowercase*

**Comment by jebuss** [comment]
Then we should stick to that

**Comment by dneise** [comment]
so `photonstream` it is? no dash no underscore?

**Comment by MaxNoe** [comment]
agreed.
