### ISSUE TITLE
Get rid of old libraries, that are already in java 8

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#220]
In our pom.xml we have dependencies that are already included in java8 in some way, e.g. 

```
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>2.7</version>
    </dependency>
````
got through the pom.xml, find out wich of them are already in Java8, delete them one by one and fix the upcoming problems.

**Comment by MaxNoe** [comment]
done in #233
