### ISSUE TITLE
Changelog Versions do not agree with tagged versions

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#227]
Our Changelog claims versions:
Version 0.18.0 -- 19.01.2017
Version 0.17.5 -- 18.01.2017
Version 0.17.4 -- 18.01.2017
Version 0.17.3 -- 17.01.2017

But the last tagged version is 0.17.2. I remember that we had problems with 0.18.0 so I guess this tag was deleted until the current streams version is fixed. However, should  tag at least versions for 0.17.3 to 0.17.5?

**Comment by MaxNoe** [comment]
This needs to be cleaned up. We did not publish a new version since v0.17.2
