### ISSUE TITLE
Refactor Calculation of Image Parameters

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#230]
Lets start with things like Width, Length, Size etc. They can be put into one single processor given the output is named in a sane way. Long ago we discussed using hierachical naming schemes. 
All image related data would be renamed to something startign with the prefix `image`. 

So this processor would output `image:length, image:width ...` etc

**Comment by MaxNoe** [comment]
I don't think we want different processors for each, one hillas parameters processor because all these values come out from the same calculations
