### ISSUE TITLE
Remove source package

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#255]
We struggled for years to do source feature reconstruction right in java.

We failed basically, because precise coordinate transformations are hard.
We now do this using astropy in our high level analysis. Which is much more flexibel.

I would propose to remove the source package, so FACT-Tools is basically just used for calibration/extraction/source independent parameterisation.

What do you think?

**Comment by dneise** [comment]
I totally agree

**Comment by MaxNoe** [comment]
It seems we (or I) gave up too early. CoordinateTrafos are now precise enough for our use case (e.g. error is smaller than a pixel).

**Comment by MaxNoe** [comment]
Kai and I decided against completely removing the code, but removing it from the standard analysis
