### ISSUE TITLE
Consider changing gains in Extraction

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#267]
Individual Pixels' gains do change over time. While some mail functions of pixels are considered in the Calibration Service, the variation of the gains is not.

In the worst case, the median camera gain varies by (30 mV slices) and the minimum gain even by (250 mV slices), in both cases this was determined on a window size of 30 slices and the generation of single pe spectra.

Here you see the time series of the gain measured in single pe spectras
![image](https://user-images.githubusercontent.com/7489182/33180121-f827a57e-d06b-11e7-9923-4fa115755a44.png)

This is the distribution of the median values of the time series above.
![image](https://user-images.githubusercontent.com/7489182/33180245-58d5f5ba-d06c-11e7-940c-df29a569e29d.png)

This is the distribution of the minima of the time series above.
![image](https://user-images.githubusercontent.com/7489182/33180240-53d3207e-d06c-11e7-84e6-a75df6e1c09a.png)

I suggest to check if these variations have to be considered and if this is the case, a gain service for the extraction algorithm.

**Comment by jebuss** [comment]
Right now I am checking how the single pe spectrum features of individual pixels change over time. Basically this would deliver the input for such a gain service.

**Comment by dneise** [comment]
I have a question. What is the uncertainty on the gain, especially for such values like the  minimum gain. 
Is a gain of ~100...150mV slices still to be considered a relevant measurement?

**Comment by jebuss** [comment]
Well thats a good question. 

Just for clarification, with minimum gain I mean the gain of the pixel with the lowest gain. 

So the uncertainty on each of theses values is the uncertainty of the gain determined from a single pixels spectrum made from 10000 triggers (aka events).

This uncertainty, I am sure how to determine that.

In an very old study I compared the gain determined from data and from MCs (see below). While the gain from data would have a systematic distribution over the pixels, for the MCs all pixel should have the same gain, since this is not varied and all pixels are simulated the same.

So judging from what you see below one could conclude that the std_dev from MCs is an rough estimate for the uncertainty of the method. Here you have a std_dev of ~3.5 mV slices calculates to an uncertainty of the mean value of  ~3.5 mV/sqrt(1439) ~ 0.9 mV slices.

![image](https://user-images.githubusercontent.com/7489182/33189472-402028b0-d0a3-11e7-9fd8-f6ac6e7caa68.png)

**Comment by jebuss** [comment]
> Is a gain of ~100...150mV slices still to be considered a relevant measurement?

Also here, I don't know for sure. At some point the maxima in the spe spectrum are too close together to distinguish between peaks, this could cause the fit of the spectrum model to fail. It's not clear to me at what minimum gain this happens. What we do have is the chi2 and ROOT's fit probability p-value. We could use those to reject gains were the fit did not work.

**Comment by MaxNoe** [comment]
Should we add a fitsfile with rows for each time period? Or how would you propose to do this without adding the need for yet another file one has to find for each run?
