### ISSUE TITLE
Cleanup unused Classes and Processors

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#277]
I would like to remove some outdated and unused classes from fact-tools

I identiefied the following candidates:

- [x] `fact.utils.PullValueFromDistribution`, author @jebuss, not used by any example and documentation unclear, last touch in 2014

- [x] `fact.auxservice.AuxWebService`, we don't have a web service for this, author @mackaiver 

- [x] `fact.utils.SelectFromArray`, this looks like it never got implemented:
https://github.com/fact-project/fact-tools/blob/07d0063e3013c97d760eac629b3652066ce044de/src/main/java/fact/utils/SelectFromArray.java#L16-L24
It basically just exits the stream by returning null

**Comment by MaxNoe** [comment]
Please comment @fact-project/fact-tools-core-dev 

Also add stuff, you think we can get rid of

**Comment by jebuss** [comment]
>  fact.utils.PullValueFromDistribution, author @jebuss, not used by any example and documentation unclear, last touch in 2014

yes kill it, can't remember why I implemented that
