### ISSUE TITLE
Option in the viewer to directly open additional windows

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#31]
Originally reported by: **ftemme (Bitbucket: [ftemme](http://bitbucket.org/ftemme), GitHub: [ftemme](http://github.com/ftemme))**

---

It would be nice, when the viewer operator has an option to directly open a new window (graph, camera, event info), when the viewer is opened. 
This would be helpful, if someone is investigating issues on the timeline and always needs the graph window directly.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/31

**Comment by MaxNoe** [comment]
We won't put anymore effort into the viewer
