### ISSUE TITLE
Drs4 Time Calibration

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#32]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

According to Fabian, neither the processor which calculates nor the processor which applies the Drs4 time calibration are sufficiently tested.
For both, tests should be done and unit tests should be implemented, so we are as sure as we can currently be, that these two are working fine.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/32

**Comment by MaxNoe** [comment]
I don't think we are touching the DRSTimeCalibration again
