### ISSUE TITLE
Make calibration.xml work with FactFileMultistream

### ISSUE THREAD

**Issue by tarrox** [fact-project/fact-tools#351]
Currently the `DrsCalibration` in the `calibration.xml` uses the `url="${drsfile}"` method of getting the drs file, which makes the xml incompatible with the use of `FactFileMultistream`. I think it would be nice if it would work with it, as it means one can just reuse it.

There are two options I can think of to make this work:

* remove the `ulr=${drsfile}` and have a processor that injects the `${drsfile}` into the datastream as the `@drsFile` item.
* by default or by parameter, make it that the `DrsCalibration`-Processor switches to the `@drsFile` option if the given url can't be read (For example because the string is empty or because it couldn't be read).

**Comment by MaxNoe** [comment]
Maybe something like:

```java
if (item.get("@drsFile") != null && url == "") {
    // use @drsFile
} else {
    // use url
}
```

**Comment by MaxNoe** [comment]
So streams does apparently not allow to create an empty or null url by setting the property to an empty string.

What I came up with was setting `-Ddrsfile=file:` and using:

```java
    @Override
    public void init(ProcessContext processContext) throws Exception {

        if (url != null)  {
            if (url.getPath() != "") {
                try {
                    loadDrsData(url);
                } catch (Exception e) {
                    log.error("Could not load .drs file specified in the url.");
                    throw new RuntimeException(e.getMessage());
                }
            } else {
                url = null;
            }
        }
    }
```

But I don't really like it. Anybody got a better idea?

**Comment by tarrox** [comment]
Another option would be to switch the url to a string and convert it if needed. That way we could set it as empty. Although this wouldn't be a good solution either, i would even say worse.

Another way would be to skip the whole init function and simply load the url if needed in the process function, basically taking `@drsfile` and if not given use the url parameter, if this fails, just abort as usual. That way we wouldn't need to check for an empty path as a way to check which method to use. Instead the drskey is always used if given.
I think this option would be the cleanest.

**Comment by MaxNoe** [comment]
> simply load the url if needed in the process function

The checking is done by streams at the xml Parsing level. The only thing would be make it a string and convert to url.
