### ISSUE TITLE
Support different output formats

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#36]
Originally reported by: **ftemme (Bitbucket: [ftemme](http://bitbucket.org/ftemme), GitHub: [ftemme](http://github.com/ftemme))**

----------------------------------------

It would be nice to have Writer processor for different output formats (for example fits, hdf5 or root output). The CSV output is (on a long way thinking) unsufficient in the order of file size and internal structure.

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/36

**Comment by MaxNoe** [comment]
Fits was also added.
