### ISSUE TITLE
Everything should use some sort of Pixelset

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#50]
Originally reported by: **mackaiver (Bitbucket: [mackaiver](http://bitbucket.org/mackaiver), GitHub: [mackaiver](http://github.com/mackaiver))**

---

Instead of annoying int arrays for pixel ids we could use instances of theCameraPixel object. Similar to the already implemented PixelSetOverlay just withoud all the drawing stuff. 

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/50

**Comment by MaxNoe** [comment]
This was implemented long ago
