### ISSUE TITLE
For loop in xml files

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#51]
Originally reported by: **ftemme (Bitbucket: [ftemme](http://bitbucket.org/ftemme), GitHub: [ftemme](http://github.com/ftemme))**

---

It would be nice to have something like a for loop in xml files. I'm thinking of something like looping over a range of numbers or looping over a list of strings:

The corresponding xml code should look like:

```
#!xml

<Loop range="1,10" step="1" indexName="counter" />
    <Processor key="name_%{data.@loop_counter}" />
</Loop>

<Loop keys="RF,SVM,NaiveBase" indexName="counter" />
    <Processor key="name_%{data.@loop_counter}" />
</Loop>
```

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/51

**Comment by MaxNoe** [comment]
This was mainly needed for source dependent calculations (off positions), which we don't do anymore. Probably not worth the effort.
