### ISSUE TITLE
3D Plotter

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#52]
Originally reported by: **Jens Buss (Bitbucket: [jebuss](http://bitbucket.org/jebuss), GitHub: [jebuss](http://github.com/jebuss))**

---

I found a nice open source plotting library (only the manual costs money) called jzy3D. It would be great to use it to quickly visualize e.g. feature vs. CHid vs. rate.

The library also offers a repo and could be integrated to our maven package.
Here is the webpage and some code examples:

http://jzy3d.org/
https://code.google.com/p/scalalab/wiki/jzy3DInScalaLab
http://www.jzy3d.org/documentation/jzy3d-quickstart.pdf

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/52

**Comment by MaxNoe** [comment]
We won't put man power into gui features anymore
