### ISSUE TITLE
FFT Backtrafo looks fishy

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#55]
Originally reported by: **Jens Buss (Bitbucket: [jebuss](http://bitbucket.org/jebuss), GitHub: [jebuss](http://github.com/jebuss))**

---

int the FFT processor the FFT Backtrafo shows only positive values. Is this intentional? Or is it a bug? this should be checked!

![Bildschirmfoto 2014-12-16 um 18.57.42.png](https://bitbucket.org/repo/EX8kqe/images/1179695080-Bildschirmfoto%202014-12-16%20um%2018.57.42.png)

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/55

**Comment by mackaiver** [comment]
Is anyone using this currently? If not I suggest to remove all FFT related stuff entirely and then reimplement it if the need arises.

**Comment by ftemme** [comment]
I found two points where there are FFT related stuff:

The processor fact.statisitics.FastFourierTrafo (which I think is used in the given example of the issue). This processor is (to my knowledge) not used currently and could be removed and reimplemented if needed.

In the processor fact.datacorrection.PatchJumpRemoval a FFT is currently used to identify ringing effects which could fake a possible Jump. By eye the finding of this ringing effects seems to work, so at the moment (as long as the processor is not reworked) it should not be removed.

**Comment by mackaiver** [comment]
@jebuss do you agree? If so I'll delete it.

**Comment by jebuss** [comment]
I think its good to have a FFT. Kai Schennetten was using it for some studies and found out something that could be interessting for fact. therefore I would keep it

**Comment by MaxNoe** [comment]
How about `deprecated because of known bug`?

**Comment by jebuss** [comment]
+1

**Comment by MaxNoe** [comment]
I think we should finally remove it now

**Comment by jebuss** [comment]
agreed
