### ISSUE TITLE
create drs4_time_file for MC analysis

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#60]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

I want to remind myself, that we also need a mockup DRS4 time calibration file for MC analysis. The current std DRS4 time calibration file contains deviations from the perfect value, so all we need in the mock-up file is a bunch of zeros.

But writing the file is ugly and I need Mars for this .... takes a couple of hours to create such a file. awesome hu?

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/60

**Comment by MaxNoe** [comment]
I don't think we will implement this, does not seem to be worth the effort.

Reopen if you feel differently.
