### ISSUE TITLE
.properties file not correctly read

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#62]
Originally reported by: **ftemme (Bitbucket: [ftemme](http://bitbucket.org/ftemme), GitHub: [ftemme](http://github.com/ftemme))**

---

When I remove the following line (52, commit: 51f69ac) in the settings.properties file, the file is not read correctly anymore:

```
#!java

stat_phChargeSat_param=phChargeSaturation_mean,phChargeSaturation_max,phChargeSaturation_min,phChargeSaturation_kurtosis,phChargeSaturation_variance,phChargeSaturation_skewness
```

The stat_phChargeSat_param property isn't used later.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/62

**Comment by cbockermann** [comment]
Bug is related to the processing order of variable expansions. The latest streams-0.9.25 SNAPSHOT version uses a custom reader and a fixed order, which should solve this problem.

**Comment by MaxNoe** [comment]
Solved
