### ISSUE TITLE
Show Points in Viewer (e.g. COG)

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#64]
Originally reported by: **Maximilian Nöthe (Bitbucket: [MaxNoe](http://bitbucket.org/MaxNoe), GitHub: [MaxNoe](http://github.com/MaxNoe))**

---

A possibility to show certain points in the viewer would be nice.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/64

**Comment by MaxNoe** [comment]
It exists.
