### ISSUE TITLE
Output File Format

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#73]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

Given that the upcoming ICRC will feature an official FACT crab spectrum, gained with fact-tools, I wonder whether it is time to create realtime analysis results on the island using fact-tools.

I understand, it is common practice in the community, to create image parameter output files, which may be used by physicists to perform their personal analysis. I understand it is not common to start off ones analysis, at the level of large raw data files, but at the level of smaller image parameter files.

I think currently, it is common practice to store these image parameters in JSON format.

It is in my opinion necessary to provide not only the results of an analysis, but also ensure reproducability and provide context. Or in other words, answer common questions like:
- what were your precuts again?
- are you sure, we used exactly the same fact-tools v0.9? 
- what forest model did you use?

I think, most questions can already be answered when having the XML and the git commit hash. (assuming that nobody would ever generate any output with a modified ans untracked fact-tools version)

I pretty much assume, there is a point of no return in this question. If we decide for a file format for these image parameters, which will turn out to be not optimal for a very common usecase, we might have to live with it.

So, what do u think? Should we stick with the current way everybody is working? Should we change something? Should we write a list of best pratices, which simply says: Make a note of what u did in the fact logbook.

What can we learn from others in the community? How is CTA going to do it? Can we do the same they will do, already today and tear down borders between experiments even before they exist?

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/73

**Comment by MaxNoe** [comment]
I think this is partly implemented and partly superceeded by our 'Eventlist' plans
