### ISSUE TITLE
Possible bug in ConcentrationCore.java

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#74]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

It seems, there was a bug in the MARS implementation of calculating, what we call the shower core concentration. The bug was apparently spotted and solved over the last weekend.

I guess, the same 'bug' should also occur in ConcentrationCore.java. 

The MARS fix was done here:
https://trac.fact-project.org/changeset/18275
if you want to look at it.

Maybe it's not wise to jump at the fix and implement it as well, but rather take the chance to deal also with the comment on line 65 of ConcentrationCore.java.
Also one must keep in mind, that the trunk version of MARS, is not the "official" version, which is used to publish results, but rather the development version. So it might well be, that this is just a test of sorts.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/74

**Comment by MaxNoe** [comment]
I think we should just reimplement ConcCore how we deem it correctly

**Comment by MaxNoe** [comment]
Fixed in #261
