### ISSUE TITLE
Two definitions of Azimuth

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#75]
Originally reported by: **mknoetig (Bitbucket: [mknoetig](http://bitbucket.org/mknoetig), GitHub: [mknoetig](http://github.com/mknoetig))**

---

Hi guys,

I was working on a comparison of MAGIC and FACT data when I wanted to rotate the Theta[x] and Theta[y] coordinates back into the sky coordinates RA/DEC. I have written down a couple of things and will present those in a more comprehensive file. For now I wanted to point out two peculiarities of our system that I had to find first..

This first issue is about the code in SourcePosition.java .There, Fabian defines implicitly a second azimuth, parallel to the one stored in container "AzTracking". This ine os called "AzPointing". 

From our discussions, following things about our azimuth got clear: 

1.) AzTracking = -180deg -AzPointing

2.) AzTracking should not be used, as it is "uncorrected", in a sense. 

Please find attached a plot displaying these issues. Maybe it would be useful, in order to get towards skymaps, to introduce a branch with proper coordinate transformations between all possible coordinate systems ( camera x/y, alt/az, ra/dec, ha/dec, ... ) that work on one consistent definition of the individual systems.  

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/75

**Comment by MaxNoe** [comment]
Also fixed by #231, we use astropys definition everywhere, Geographic North is 0°
