### ISSUE TITLE
The confusing definition of the FACT camera coordinate system

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#76]
Originally reported by: **mknoetig (Bitbucket: [mknoetig](http://bitbucket.org/mknoetig), GitHub: [mknoetig](http://github.com/mknoetig))**

---

Hi guys,

this is a continuation from [two-definitions-of-azimuth](https://bitbucket.org/cbockermann/fact-tools/issues/75/two-definitions-of-azimuth)

I was working on a comparison of MAGIC and FACT data when I wanted to rotate the Theta[x] and Theta[y] coordinates back into the sky coordinates RA/DEC. I have written down a couple of things and will present those in a more comprehensive file. For now I wanted to point out two peculiarities of our system that I had to find first..

The second peculiarity was the definition of the FACT camera coordinate system. People told me it is what is is, because of reasons. I wanted to make a small plot, explaining it. So here it is. Guess in this case we just have to live with it. However, if in the future anybody is wondering WTF, I hope this post helps.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/76

**Comment by MaxNoe** [comment]
This will be fixed by #249
