### ISSUE TITLE
Proposal for a complete set of coordinate (transformations)

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#77]
Originally reported by: **mknoetig (Bitbucket: [mknoetig](http://bitbucket.org/mknoetig), GitHub: [mknoetig](http://github.com/mknoetig))**

---

I am interested in skymaps. After all, we are **astro**-particle physiscists..

For this we would need a set of coordinate transformations, which should be as general as possible. For this I would like to start working on a new branch with the intention to implement the following. In an Alt/Az telescope, such as FACT, a couple of coordinate systems appear interesting.

A first draft of the list of needed transformations is something like:

Do you find this interesting/useful?

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/77

**Comment by MaxNoe** [comment]
I started implementing this in #231

**Comment by MaxNoe** [comment]
Fixed by merging #231 several weeks ago
