### ISSUE TITLE
RTA at La Palma

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#81]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---

Hey,

once the fact-tools RTA is running on La Palma, I guess one will create some kind of web-front-end for the results.

I think it would be cool, if passers by could click on light curve points in order to look at events in the runs in question. 

Consider this Lightcurve of 2344 of a couple of days ago.
 ![1ES_2344_flair_maybe.png](https://bitbucket.org/repo/EX8kqe/images/971989043-1ES_2344_flair_maybe.png)

Two runs look like the source flaired, but both of them show the same rate, which is maybe a bit suspicious. I immediately wanted to look at the 12 excess events, which should be inside this run. So if the fact-tools RTA web-front-end would have such a feature, maybe people would like it better than the other.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/81

**Comment by MaxNoe** [comment]
RTA is now running. Needs to be merged to master though and as a lot of room for improvement. Closing for now.
