### ISSUE TITLE
missing viewer features

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#82]
Originally reported by: **Dominik Neise (Bitbucket: [dneise](http://bitbucket.org/dneise), GitHub: [dneise](http://github.com/dneise))**

---
## Pseudo-Random-Access to events in the viewer

I think, it would help a lot, if people could jump backwards a couple of events, or skip forward to events with a certain trigger-type.
## Auto loop through time series in an event

Often when clicking through a large number of events, one wants to _see_ the temporal aspect of a shower. So one does:
- click on next
- move the slider a bit
  Repeatedly. By auto looping the slider, one could get rid of this nuisance.
## Viewer plot windows should scale

Using the viewer on a single monitor laptop screen on 1680x1050 is nearly impossible, If one wants to simultaneously look at:
- number of photons camera plot
- arrival time camera plot
- amplitude video (in an auto loop)
- A single waveform of a couple selected of pixels
- ans still be able to click the 'next' button

However it would be possible, if the camera plots were scalable. 
## Get rid of the fixed view of the all-camera-average time series

Maybe there is no such thing as, something everybody wants to see. I think the main window of the viewer should not contain the all camera average of the time series, since it only wastes precious space on the screen. 
## Get the textual information about the entire data item back.

Recently I wanted to learn the time an event was triggered. It is stored in the Fits file by the stupid tuple "UtcTime" = (seconds since 1.1.1970, microseconds) or so. So its definitely there. But I can't get this information from the viewer.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/82

**Comment by MaxNoe** [comment]
We are not touching the viewer anymore
