### ISSUE TITLE
Create processor to align MC output to real data

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#85]
Originally reported by: **mackaiver (Bitbucket: [mackaiver](http://bitbucket.org/mackaiver), GitHub: [mackaiver](http://github.com/mackaiver))**

---

As the title says it would be useful to have a processor which creates artificial timestamps etc so the monte carlo data looks more like real data. Good defaults have to be defined for artificial keys in the data stream.

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/85

**Comment by MaxNoe** [comment]
We discussed it further and concluded that it's not feasible to assign realistic observation times to our mcs
