### ISSUE TITLE
naming Consistency

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#86]
Originally reported by: **Jens Buss (Bitbucket: [jebuss](http://bitbucket.org/jebuss), GitHub: [jebuss](http://github.com/jebuss))**

----------------------------------------

Make sure that we use the same naming for the same things e.g. set of pixels, voltage curve.

So far we have the following conventions:

**pixelSet** - set of pixels that have common properties (shower pixel, bad pixel, ...)

**timeSeries** - term for the curve time vs. voltage as measure for the el. signal in the pixels

**?** - photon charge 

**?** - term for the data item object in the process method

* Methods in Java: CamelCase but with leading lower case, so camelCase

----------------------------------------
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/86

**Comment by ftemme** [comment]
The naming consistency we choosed is described in #107 and will be applied during the refactoring
