### ISSUE TITLE
Rework the outputkeys

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#91]
Originally reported by: **ftemme (Bitbucket: [ftemme](http://bitbucket.org/ftemme), GitHub: [ftemme](http://github.com/ftemme))**

---

There is at least the RUNID key missing in the list of outputkeys in the std Analysis for MCs. (Defined in settings_mc.properties). The settings.properties files could maybe be reworked with the next facttools version.
Also missing some MC truth keys, for example IncidentAngle.fVal ...

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/91

**Comment by MaxNoe** [comment]
We had a big rework in #315 and the CeresStream fixes the missing simulation truth for mcs
