### ISSUE TITLE
FITS writer

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#94]
This would be useful for quite some situations.

**Comment by dneise** [comment]
:+1:

**Comment by MaxNoe** [comment]
http://nom-tam-fits.github.io/nom-tam-fits/intro.html

**Comment by dneise** [comment]
this nom-tam part makes it sound funny ... why not just fits?

**Comment by alexeyegorov** [comment]
I've made a pull request for writing FITS files using nom-tam-tam-tam FITS library. Tests are failing, but due to missing drs file. This happened first after I pulled newest changes from refactoring branch.

**Comment by alexeyegorov** [comment]
There are some field, that we seem not use right now while reading FITS, such as PCOUNT or GCOUNT. They seem to be required normally? This would be important for the case if we would like to replace our FITS reader with nom-tam-fits reader.

**Comment by MaxNoe** [comment]
This was added in #138
