### ISSUE TITLE
Update webpage

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#97]
Our webpage still links to bitbucket:
http://sfb876.tu-dortmund.de/FACT/

**Comment by MaxNoe** [comment]
Maybe we also want to additionally provide http://sfb876.tu-dortmund.de/fact-tools?

**Comment by MaxNoe** [comment]
see #99

**Comment by mackaiver** [comment]
I'd prefer build a new website using github pages. Maybe using the latest Jekyll. What do you think?

**Comment by MaxNoe** [comment]
This will be usefull then:
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by MaxNoe** [comment]
#101
